development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sellerauction_development
  pool: 5
  username: devuser
  password: devpass
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sellerauction_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sellerauction_production
  pool: 5
  username: user
  password: -wee
  host: 127.0.0.1
